services:
  iggy:
    environment:
      IGGY_DATA_MAINTENANCE_MESSAGES_CLEANER_ENABLED: "true"
      IGGY_DATA_MAINTENANCE_MESSAGES_INTERVAL: "1 s"
      IGGY_MESSAGE_SAVER_ENABLED: "true"
      IGGY_MESSAGE_SAVER_ENFORCE_FSYNC: "true"
      IGGY_MESSAGE_SAVER_INTERVAL: "1 s"
      IGGY_SYSTEM_PARTITION_ENFORCE_FSYNC: "true"
      IGGY_SYSTEM_PARTITION_MESSAGES_REQUIRED_TO_SAVE: "1"
      IGGY_SYSTEM_SEGMENT_SIZE: "1 KB"
      IGGY_SYSTEM_STATE_ENFORCE_FSYNC: "true"
      IGGY_SYSTEM_MESSAGE_DEDUPLICATION_ENABLED: "true"
      IGGY_SYSTEM_MESSAGE_DEDUPLICATION_MAX_ENTRIES: "10000"
      IGGY_SYSTEM_MESSAGE_DEDUPLICATION_EXPIRY: "24 h"
