// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion, dead_code
library frf;

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

final class _RustBuffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Uint64()
  external int len;
}

final class _UniFfiFfiBufferElement extends ffi.Union {
  @ffi.Uint8()
  external int u8;

  @ffi.Int8()
  external int i8;

  @ffi.Uint16()
  external int u16;

  @ffi.Int16()
  external int i16;

  @ffi.Uint32()
  external int u32;

  @ffi.Int32()
  external int i32;

  @ffi.Uint64()
  external int u64;

  @ffi.Int64()
  external int i64;

  @ffi.Float()
  external double float32;

  @ffi.Double()
  external double float64;

  external ffi.Pointer<ffi.Void> ptr;
}

final class _UniFfiRustBuffer extends ffi.Struct {
  @ffi.Uint64()
  external int capacity;

  @ffi.Uint64()
  external int len;

  external ffi.Pointer<ffi.Uint8> data;
}

final class _UniFfiForeignBytes extends ffi.Struct {
  @ffi.Int32()
  external int len;

  external ffi.Pointer<ffi.Uint8> data;
}

final class _UniFfiRustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external _UniFfiRustBuffer errorBuf;
}

const int _uniFfiRustCallStatusSuccess = 0;
const int _uniFfiRustCallStatusError = 1;
const int _uniFfiRustCallStatusUnexpectedError = 2;
const int _uniFfiRustCallStatusCancelled = 3;

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
const int _rustFuturePollReady = 0;
const int _rustFuturePollWake = 1;

/// Errors surfaced by the client transport FFI (connect/publish/subscribe).
sealed class ClientFfiError {
  const ClientFfiError();
}

final class ClientFfiErrorConnect extends ClientFfiError {
  const ClientFfiErrorConnect();

  @override
  String toString() {
    return 'ClientFfiErrorConnect()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientFfiErrorConnect;

  @override
  int get hashCode => runtimeType.hashCode;
}

final class ClientFfiErrorRequest extends ClientFfiError {
  const ClientFfiErrorRequest();

  @override
  String toString() {
    return 'ClientFfiErrorRequest()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientFfiErrorRequest;

  @override
  int get hashCode => runtimeType.hashCode;
}

final class ClientFfiErrorInvalidArgument extends ClientFfiError {
  const ClientFfiErrorInvalidArgument();

  @override
  String toString() {
    return 'ClientFfiErrorInvalidArgument()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientFfiErrorInvalidArgument;

  @override
  int get hashCode => runtimeType.hashCode;
}

sealed class CrdtFfiError {
  const CrdtFfiError();
}

final class CrdtFfiErrorApplyDelta extends CrdtFfiError {
  const CrdtFfiErrorApplyDelta();

  @override
  String toString() {
    return 'CrdtFfiErrorApplyDelta()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrdtFfiErrorApplyDelta;

  @override
  int get hashCode => runtimeType.hashCode;
}

final class CrdtFfiErrorEncode extends CrdtFfiError {
  const CrdtFfiErrorEncode();

  @override
  String toString() {
    return 'CrdtFfiErrorEncode()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrdtFfiErrorEncode;

  @override
  int get hashCode => runtimeType.hashCode;
}

final class CrdtFfiErrorDecode extends CrdtFfiError {
  const CrdtFfiErrorDecode();

  @override
  String toString() {
    return 'CrdtFfiErrorDecode()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrdtFfiErrorDecode;

  @override
  int get hashCode => runtimeType.hashCode;
}

/// Errors surfaced by the client transport FFI (connect/publish/subscribe).
sealed class ClientFfiErrorException implements Exception {
  const ClientFfiErrorException();
}

final class ClientFfiErrorExceptionConnect extends ClientFfiErrorException {
  const ClientFfiErrorExceptionConnect();

  @override
  String toString() {
    return 'ClientFfiErrorExceptionConnect()';
  }
}

final class ClientFfiErrorExceptionRequest extends ClientFfiErrorException {
  const ClientFfiErrorExceptionRequest();

  @override
  String toString() {
    return 'ClientFfiErrorExceptionRequest()';
  }
}

final class ClientFfiErrorExceptionInvalidArgument extends ClientFfiErrorException {
  const ClientFfiErrorExceptionInvalidArgument();

  @override
  String toString() {
    return 'ClientFfiErrorExceptionInvalidArgument()';
  }
}

ClientFfiErrorException _uniffiLiftClientFfiErrorException(Uint8List bytes) {
  final ClientFfiError value = _uniffiDecodeClientFfiError(bytes);
  if (value is ClientFfiErrorConnect) return const ClientFfiErrorExceptionConnect();
  if (value is ClientFfiErrorRequest) return const ClientFfiErrorExceptionRequest();
  if (value is ClientFfiErrorInvalidArgument) return const ClientFfiErrorExceptionInvalidArgument();
  throw StateError('Unknown ClientFfiError error variant while lifting exception: $value');
}

sealed class CrdtFfiErrorException implements Exception {
  const CrdtFfiErrorException();
}

final class CrdtFfiErrorExceptionApplyDelta extends CrdtFfiErrorException {
  const CrdtFfiErrorExceptionApplyDelta();

  @override
  String toString() {
    return 'CrdtFfiErrorExceptionApplyDelta()';
  }
}

final class CrdtFfiErrorExceptionEncode extends CrdtFfiErrorException {
  const CrdtFfiErrorExceptionEncode();

  @override
  String toString() {
    return 'CrdtFfiErrorExceptionEncode()';
  }
}

final class CrdtFfiErrorExceptionDecode extends CrdtFfiErrorException {
  const CrdtFfiErrorExceptionDecode();

  @override
  String toString() {
    return 'CrdtFfiErrorExceptionDecode()';
  }
}

CrdtFfiErrorException _uniffiLiftCrdtFfiErrorException(Uint8List bytes) {
  final CrdtFfiError value = _uniffiDecodeCrdtFfiError(bytes);
  if (value is CrdtFfiErrorApplyDelta) return const CrdtFfiErrorExceptionApplyDelta();
  if (value is CrdtFfiErrorEncode) return const CrdtFfiErrorExceptionEncode();
  if (value is CrdtFfiErrorDecode) return const CrdtFfiErrorExceptionDecode();
  throw StateError('Unknown CrdtFfiError error variant while lifting exception: $value');
}

String _encodeClientFfiError(ClientFfiError value) {
  if (value is ClientFfiErrorConnect) {
    return jsonEncode({
      'tag': 'connect',
    });
  }
  if (value is ClientFfiErrorRequest) {
    return jsonEncode({
      'tag': 'request',
    });
  }
  if (value is ClientFfiErrorInvalidArgument) {
    return jsonEncode({
      'tag': 'invalidArgument',
    });
  }
  throw StateError('Unknown ClientFfiError variant instance: $value');
}

ClientFfiError _decodeClientFfiError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'connect':
      return ClientFfiErrorConnect(
      );
    case 'request':
      return ClientFfiErrorRequest(
      );
    case 'invalidArgument':
      return ClientFfiErrorInvalidArgument(
      );
    default:
      throw StateError('Unknown ClientFfiError variant tag: $tag');
  }
}

String _encodeCrdtFfiError(CrdtFfiError value) {
  if (value is CrdtFfiErrorApplyDelta) {
    return jsonEncode({
      'tag': 'applyDelta',
    });
  }
  if (value is CrdtFfiErrorEncode) {
    return jsonEncode({
      'tag': 'encode',
    });
  }
  if (value is CrdtFfiErrorDecode) {
    return jsonEncode({
      'tag': 'decode',
    });
  }
  throw StateError('Unknown CrdtFfiError variant instance: $value');
}

CrdtFfiError _decodeCrdtFfiError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'applyDelta':
      return CrdtFfiErrorApplyDelta(
      );
    case 'encode':
      return CrdtFfiErrorEncode(
      );
    case 'decode':
      return CrdtFfiErrorDecode(
      );
    default:
      throw StateError('Unknown CrdtFfiError variant tag: $tag');
  }
}

String _encodeClientFfiErrorException(ClientFfiErrorException value) {
  if (value is ClientFfiErrorExceptionConnect) {
    return jsonEncode({
      'tag': 'connect',
    });
  }
  if (value is ClientFfiErrorExceptionRequest) {
    return jsonEncode({
      'tag': 'request',
    });
  }
  if (value is ClientFfiErrorExceptionInvalidArgument) {
    return jsonEncode({
      'tag': 'invalidArgument',
    });
  }
  throw StateError('Unknown ClientFfiErrorException exception instance: $value');
}

ClientFfiErrorException _decodeClientFfiErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'connect':
      return const ClientFfiErrorExceptionConnect();
    case 'request':
      return const ClientFfiErrorExceptionRequest();
    case 'invalidArgument':
      return const ClientFfiErrorExceptionInvalidArgument();
    default:
      throw StateError('Unknown ClientFfiErrorException exception tag: $tag');
  }
}

String _encodeCrdtFfiErrorException(CrdtFfiErrorException value) {
  if (value is CrdtFfiErrorExceptionApplyDelta) {
    return jsonEncode({
      'tag': 'applyDelta',
    });
  }
  if (value is CrdtFfiErrorExceptionEncode) {
    return jsonEncode({
      'tag': 'encode',
    });
  }
  if (value is CrdtFfiErrorExceptionDecode) {
    return jsonEncode({
      'tag': 'decode',
    });
  }
  throw StateError('Unknown CrdtFfiErrorException exception instance: $value');
}

CrdtFfiErrorException _decodeCrdtFfiErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'applyDelta':
      return const CrdtFfiErrorExceptionApplyDelta();
    case 'encode':
      return const CrdtFfiErrorExceptionEncode();
    case 'decode':
      return const CrdtFfiErrorExceptionDecode();
    default:
      throw StateError('Unknown CrdtFfiErrorException exception tag: $tag');
  }
}

final class ClientFfiErrorFfiCodec {
  const ClientFfiErrorFfiCodec._();

  static String encode(ClientFfiError value) => _encodeClientFfiError(value);

  static ClientFfiError decode(String raw) => _decodeClientFfiError(raw);
}

final class CrdtFfiErrorFfiCodec {
  const CrdtFfiErrorFfiCodec._();

  static String encode(CrdtFfiError value) => _encodeCrdtFfiError(value);

  static CrdtFfiError decode(String raw) => _decodeCrdtFfiError(raw);
}

final class ClientFfiErrorExceptionFfiCodec {
  const ClientFfiErrorExceptionFfiCodec._();

  static String encode(ClientFfiErrorException value) => _encodeClientFfiErrorException(value);

  static ClientFfiErrorException decode(Object? raw) => _decodeClientFfiErrorException(raw);
}

final class CrdtFfiErrorExceptionFfiCodec {
  const CrdtFfiErrorExceptionFfiCodec._();

  static String encode(CrdtFfiErrorException value) => _encodeCrdtFfiErrorException(value);

  static CrdtFfiErrorException decode(Object? raw) => _decodeCrdtFfiErrorException(raw);
}

final class _UniFfiBinaryWriter {
  final BytesBuilder _builder = BytesBuilder(copy: false);

  void writeU8(int value) => _builder.add([value & 0xFF]);
  void writeI8(int value) => _builder.add([(value) & 0xFF]);
  void writeU16(int value) {
    final data = ByteData(2)..setUint16(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI16(int value) {
    final data = ByteData(2)..setInt16(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeU32(int value) {
    final data = ByteData(4)..setUint32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI32(int value) {
    final data = ByteData(4)..setInt32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeU64(int value) {
    final data = ByteData(8)..setUint64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI64(int value) {
    final data = ByteData(8)..setInt64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeF32(double value) {
    final data = ByteData(4)..setFloat32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeF64(double value) {
    final data = ByteData(8)..setFloat64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeBool(bool value) => writeI8(value ? 1 : 0);
  void writeBytes(Uint8List bytes) => _builder.add(bytes);
  void writeString(String value) {
    final bytes = Uint8List.fromList(utf8.encode(value));
    writeI32(bytes.length);
    writeBytes(bytes);
  }

  Uint8List toBytes() => _builder.takeBytes();
}

final class _UniFfiBinaryReader {
  _UniFfiBinaryReader(this._bytes);
  final Uint8List _bytes;
  int _offset = 0;

  bool get isDone => _offset == _bytes.length;

  ByteData _readData(int len) {
    if (_offset + len > _bytes.length) {
      throw StateError('buffer underflow while decoding UniFFI payload');
    }
    final data = ByteData.sublistView(_bytes, _offset, _offset + len);
    _offset += len;
    return data;
  }

  int readU8() => _readData(1).getUint8(0);
  int readI8() => _readData(1).getInt8(0);
  int readU16() => _readData(2).getUint16(0, Endian.big);
  int readI16() => _readData(2).getInt16(0, Endian.big);
  int readU32() => _readData(4).getUint32(0, Endian.big);
  int readI32() => _readData(4).getInt32(0, Endian.big);
  int readU64() => _readData(8).getUint64(0, Endian.big);
  int readI64() => _readData(8).getInt64(0, Endian.big);
  double readF32() => _readData(4).getFloat32(0, Endian.big);
  double readF64() => _readData(8).getFloat64(0, Endian.big);
  bool readBool() {
    final value = readI8();
    if (value == 0) return false;
    if (value == 1) return true;
    throw StateError('invalid boolean payload value: $value');
  }
  Uint8List readBytes(int len) {
    if (_offset + len > _bytes.length) {
      throw StateError('buffer underflow while decoding UniFFI payload bytes');
    }
    final out = Uint8List.fromList(_bytes.sublist(_offset, _offset + len));
    _offset += len;
    return out;
  }
  String readString() {
    final len = readI32();
    if (len < 0) {
      throw StateError('invalid string length in UniFFI payload: $len');
    }
    return utf8.decode(readBytes(len));
  }
}

void _uniffiWriteClientFfiError(ClientFfiError value, _UniFfiBinaryWriter writer) {
  if (value is ClientFfiErrorConnect) {
    writer.writeI32(1);
  }
  else if (value is ClientFfiErrorRequest) {
    writer.writeI32(2);
  }
  else if (value is ClientFfiErrorInvalidArgument) {
    writer.writeI32(3);
  }
  else {
    throw StateError('Unknown ClientFfiError variant instance: $value');
  }
}

Uint8List _uniffiEncodeClientFfiError(ClientFfiError value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteClientFfiError(value, writer);
  return writer.toBytes();
}

ClientFfiError _uniffiReadClientFfiError(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return const ClientFfiErrorConnect();
    case 2:
      return const ClientFfiErrorRequest();
    case 3:
      return const ClientFfiErrorInvalidArgument();
    default:
      throw StateError('Unknown ClientFfiError variant tag: $tag');
  }
}

ClientFfiError _uniffiDecodeClientFfiError(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadClientFfiError(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding ClientFfiError');
  }
  return value;
}

void _uniffiWriteCrdtFfiError(CrdtFfiError value, _UniFfiBinaryWriter writer) {
  if (value is CrdtFfiErrorApplyDelta) {
    writer.writeI32(1);
  }
  else if (value is CrdtFfiErrorEncode) {
    writer.writeI32(2);
  }
  else if (value is CrdtFfiErrorDecode) {
    writer.writeI32(3);
  }
  else {
    throw StateError('Unknown CrdtFfiError variant instance: $value');
  }
}

Uint8List _uniffiEncodeCrdtFfiError(CrdtFfiError value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteCrdtFfiError(value, writer);
  return writer.toBytes();
}

CrdtFfiError _uniffiReadCrdtFfiError(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return const CrdtFfiErrorApplyDelta();
    case 2:
      return const CrdtFfiErrorEncode();
    case 3:
      return const CrdtFfiErrorDecode();
    default:
      throw StateError('Unknown CrdtFfiError variant tag: $tag');
  }
}

CrdtFfiError _uniffiDecodeCrdtFfiError(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadCrdtFfiError(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding CrdtFfiError');
  }
  return value;
}

class FrfFfi {
  FrfFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_frf';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_frf_ffi_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_frf_ffi_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_frf_ffi_checksum_func_crdt_apply_delta;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_func_crdt_apply_delta');
      _checksum_uniffi_frf_ffi_checksum_func_crdt_apply_delta = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_func_crdt_apply_delta`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_func_crdt_apply_delta != 35537) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_func_crdt_apply_delta`: expected 35537, got $_checksum_uniffi_frf_ffi_checksum_func_crdt_apply_delta');
    }
    final int _checksum_uniffi_frf_ffi_checksum_func_crdt_new_snapshot;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_func_crdt_new_snapshot');
      _checksum_uniffi_frf_ffi_checksum_func_crdt_new_snapshot = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_func_crdt_new_snapshot`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_func_crdt_new_snapshot != 32658) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_func_crdt_new_snapshot`: expected 32658, got $_checksum_uniffi_frf_ffi_checksum_func_crdt_new_snapshot');
    }
    final int _checksum_uniffi_frf_ffi_checksum_func_crdt_snapshot_version;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_func_crdt_snapshot_version');
      _checksum_uniffi_frf_ffi_checksum_func_crdt_snapshot_version = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_func_crdt_snapshot_version`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_func_crdt_snapshot_version != 2276) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_func_crdt_snapshot_version`: expected 2276, got $_checksum_uniffi_frf_ffi_checksum_func_crdt_snapshot_version');
    }
    final int _checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_event;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_method_eventcallback_on_event');
      _checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_event = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_method_eventcallback_on_event`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_event != 63298) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_method_eventcallback_on_event`: expected 63298, got $_checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_event');
    }
    final int _checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_error;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_method_eventcallback_on_error');
      _checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_error = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_method_eventcallback_on_error`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_error != 30065) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_method_eventcallback_on_error`: expected 30065, got $_checksum_uniffi_frf_ffi_checksum_method_eventcallback_on_error');
    }
    final int _checksum_uniffi_frf_ffi_checksum_method_frffficlient_ack;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_method_frffficlient_ack');
      _checksum_uniffi_frf_ffi_checksum_method_frffficlient_ack = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_method_frffficlient_ack`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_method_frffficlient_ack != 8100) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_method_frffficlient_ack`: expected 8100, got $_checksum_uniffi_frf_ffi_checksum_method_frffficlient_ack');
    }
    final int _checksum_uniffi_frf_ffi_checksum_method_frffficlient_publish;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_method_frffficlient_publish');
      _checksum_uniffi_frf_ffi_checksum_method_frffficlient_publish = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_method_frffficlient_publish`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_method_frffficlient_publish != 47291) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_method_frffficlient_publish`: expected 47291, got $_checksum_uniffi_frf_ffi_checksum_method_frffficlient_publish');
    }
    final int _checksum_uniffi_frf_ffi_checksum_method_frffficlient_subscribe;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_method_frffficlient_subscribe');
      _checksum_uniffi_frf_ffi_checksum_method_frffficlient_subscribe = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_method_frffficlient_subscribe`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_method_frffficlient_subscribe != 61724) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_method_frffficlient_subscribe`: expected 61724, got $_checksum_uniffi_frf_ffi_checksum_method_frffficlient_subscribe');
    }
    final int _checksum_uniffi_frf_ffi_checksum_constructor_frffficlient_connect;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_frf_ffi_checksum_constructor_frffficlient_connect');
      _checksum_uniffi_frf_ffi_checksum_constructor_frffficlient_connect = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_frf_ffi_checksum_constructor_frffficlient_connect`: $err');
    }
    if (_checksum_uniffi_frf_ffi_checksum_constructor_frffficlient_connect != 54094) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_frf_ffi_checksum_constructor_frffficlient_connect`: expected 54094, got $_checksum_uniffi_frf_ffi_checksum_constructor_frffficlient_connect');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final void Function(_RustBuffer) _rustBytesFree = _lib.lookupFunction<ffi.Void Function(_RustBuffer), void Function(_RustBuffer)>('rust_bytes_free');

  late final _UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _uniFfiRustBufferFromBytes = _lib.lookupFunction<_UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus), _UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_frf_rustbuffer_from_bytes');
  late final void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _uniFfiRustBufferFree = _lib.lookupFunction<ffi.Void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus), void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_frf_rustbuffer_free');

  late final void Function(ffi.Pointer<_EventCallbackTraitVTable>) _eventCallbackTraitCallbackInit = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_EventCallbackTraitVTable>), void Function(ffi.Pointer<_EventCallbackTraitVTable>)>('eventcallback_trait_callback_init');
  late final ffi.Pointer<_EventCallbackTraitVTable> _eventCallbackTraitCallbackVTable = _EventCallbackTraitCallbackBridge.createVTable();
  late final bool _eventCallbackTraitCallbackInitDone = (() {
    _eventCallbackTraitCallbackInit(_eventCallbackTraitCallbackVTable);
    return true;
  })();

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _crdtApplyDeltaFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_func_crdt_apply_delta');

  Uint8List crdtApplyDelta(Uint8List existing, Uint8List delta) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(6);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List existingBytes = existing;
      final ffi.Pointer<ffi.Uint8> existingPtr = existingBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(existingBytes.length);
      if (existingBytes.isNotEmpty) { existingPtr.asTypedList(existingBytes.length).setAll(0, existingBytes); }
      foreignArgPtrs.add(existingPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> existingFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      existingFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      existingFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> existingForeignPtr = calloc<_UniFfiForeignBytes>();
      existingForeignPtr.ref
        ..len = existingBytes.length
        ..data = existingPtr;
      final _UniFfiRustBuffer existingRustBuffer = _uniFfiRustBufferFromBytes(existingForeignPtr.ref, existingFromBytesStatusPtr);
      calloc.free(existingForeignPtr);
      final int existingFromBytesCode = existingFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer existingFromBytesErrBuf = existingFromBytesStatusPtr.ref.errorBuf;
      calloc.free(existingFromBytesStatusPtr);
      if (existingFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> existingFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        existingFromBytesErrBufPtr.ref
          ..capacity = existingFromBytesErrBuf.capacity
          ..len = existingFromBytesErrBuf.len
          ..data = existingFromBytesErrBuf.data;
        rustRetBufferPtrs.add(existingFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $existingFromBytesCode');
      }
      (argBuf + 0).ref.u64 = existingRustBuffer.capacity;
      (argBuf + 1).ref.u64 = existingRustBuffer.len;
      (argBuf + 2).ref.ptr = existingRustBuffer.data.cast<ffi.Void>();
      final Uint8List deltaBytes = delta;
      final ffi.Pointer<ffi.Uint8> deltaPtr = deltaBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(deltaBytes.length);
      if (deltaBytes.isNotEmpty) { deltaPtr.asTypedList(deltaBytes.length).setAll(0, deltaBytes); }
      foreignArgPtrs.add(deltaPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> deltaFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      deltaFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      deltaFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> deltaForeignPtr = calloc<_UniFfiForeignBytes>();
      deltaForeignPtr.ref
        ..len = deltaBytes.length
        ..data = deltaPtr;
      final _UniFfiRustBuffer deltaRustBuffer = _uniFfiRustBufferFromBytes(deltaForeignPtr.ref, deltaFromBytesStatusPtr);
      calloc.free(deltaForeignPtr);
      final int deltaFromBytesCode = deltaFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer deltaFromBytesErrBuf = deltaFromBytesStatusPtr.ref.errorBuf;
      calloc.free(deltaFromBytesStatusPtr);
      if (deltaFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> deltaFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        deltaFromBytesErrBufPtr.ref
          ..capacity = deltaFromBytesErrBuf.capacity
          ..len = deltaFromBytesErrBuf.len
          ..data = deltaFromBytesErrBuf.data;
        rustRetBufferPtrs.add(deltaFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $deltaFromBytesCode');
      }
      (argBuf + 3).ref.u64 = deltaRustBuffer.capacity;
      (argBuf + 4).ref.u64 = deltaRustBuffer.len;
      (argBuf + 5).ref.ptr = deltaRustBuffer.data.cast<ffi.Void>();
      _crdtApplyDeltaFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftCrdtFfiErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = retBytes;
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _crdtNewSnapshotFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_func_crdt_new_snapshot');

  Uint8List crdtNewSnapshot() {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(0);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      _crdtNewSnapshotFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftCrdtFfiErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = retBytes;
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _crdtSnapshotVersionFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_func_crdt_snapshot_version');

  int crdtSnapshotVersion(Uint8List snapshot) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List snapshotBytes = snapshot;
      final ffi.Pointer<ffi.Uint8> snapshotPtr = snapshotBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(snapshotBytes.length);
      if (snapshotBytes.isNotEmpty) { snapshotPtr.asTypedList(snapshotBytes.length).setAll(0, snapshotBytes); }
      foreignArgPtrs.add(snapshotPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> snapshotFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      snapshotFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      snapshotFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> snapshotForeignPtr = calloc<_UniFfiForeignBytes>();
      snapshotForeignPtr.ref
        ..len = snapshotBytes.length
        ..data = snapshotPtr;
      final _UniFfiRustBuffer snapshotRustBuffer = _uniFfiRustBufferFromBytes(snapshotForeignPtr.ref, snapshotFromBytesStatusPtr);
      calloc.free(snapshotForeignPtr);
      final int snapshotFromBytesCode = snapshotFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer snapshotFromBytesErrBuf = snapshotFromBytesStatusPtr.ref.errorBuf;
      calloc.free(snapshotFromBytesStatusPtr);
      if (snapshotFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> snapshotFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        snapshotFromBytesErrBufPtr.ref
          ..capacity = snapshotFromBytesErrBuf.capacity
          ..len = snapshotFromBytesErrBuf.len
          ..data = snapshotFromBytesErrBuf.data;
        rustRetBufferPtrs.add(snapshotFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $snapshotFromBytesCode');
      }
      (argBuf + 0).ref.u64 = snapshotRustBuffer.capacity;
      (argBuf + 1).ref.u64 = snapshotRustBuffer.len;
      (argBuf + 2).ref.ptr = snapshotRustBuffer.data.cast<ffi.Void>();
      _crdtSnapshotVersionFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u64;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _eventCallbackFreeRaw = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), void Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('uniffi_frf_ffi_fn_free_eventcallback');
  late final void Function(int handle) _eventCallbackFree = (int handle) {
    final statusPtr = calloc<_UniFfiRustCallStatus>();
    statusPtr.ref.code = _uniFfiRustCallStatusSuccess;
    statusPtr.ref.errorBuf
      ..capacity = 0
      ..len = 0
      ..data = ffi.nullptr;
    _eventCallbackFreeRaw(handle, statusPtr);
    calloc.free(statusPtr);
  };

  late final int Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _eventCallbackClone = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), int Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('uniffi_frf_ffi_fn_clone_eventcallback');

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _eventCallbackOnErrorFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_method_eventcallback_on_error');

  void eventCallbackInvokeOnError(int handle, String message) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(4);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(4);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final int clonedHandle;
      {
        final cloneStatusPtr = calloc<_UniFfiRustCallStatus>();
        try {
          cloneStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
          cloneStatusPtr.ref.errorBuf
            ..capacity = 0
            ..len = 0
            ..data = ffi.nullptr;
          clonedHandle = _eventCallbackClone(handle, cloneStatusPtr);
          if (cloneStatusPtr.ref.code != _uniFfiRustCallStatusSuccess) {
            throw StateError('UniFFI clone failed with status ${cloneStatusPtr.ref.code}');
          }
        } finally {
          calloc.free(cloneStatusPtr);
        }
      }
      (argBuf + 0).ref.u64 = clonedHandle;
      final Uint8List messageBytes = Uint8List.fromList(utf8.encode(message));
      final ffi.Pointer<ffi.Uint8> messagePtr = messageBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(messageBytes.length);
      if (messageBytes.isNotEmpty) { messagePtr.asTypedList(messageBytes.length).setAll(0, messageBytes); }
      foreignArgPtrs.add(messagePtr);
      final ffi.Pointer<_UniFfiRustCallStatus> messageFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      messageFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      messageFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> messageForeignPtr = calloc<_UniFfiForeignBytes>();
      messageForeignPtr.ref
        ..len = messageBytes.length
        ..data = messagePtr;
      final _UniFfiRustBuffer messageRustBuffer = _uniFfiRustBufferFromBytes(messageForeignPtr.ref, messageFromBytesStatusPtr);
      calloc.free(messageForeignPtr);
      final int messageFromBytesCode = messageFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer messageFromBytesErrBuf = messageFromBytesStatusPtr.ref.errorBuf;
      calloc.free(messageFromBytesStatusPtr);
      if (messageFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> messageFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        messageFromBytesErrBufPtr.ref
          ..capacity = messageFromBytesErrBuf.capacity
          ..len = messageFromBytesErrBuf.len
          ..data = messageFromBytesErrBuf.data;
        rustRetBufferPtrs.add(messageFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $messageFromBytesCode');
      }
      (argBuf + 1).ref.u64 = messageRustBuffer.capacity;
      (argBuf + 2).ref.u64 = messageRustBuffer.len;
      (argBuf + 3).ref.ptr = messageRustBuffer.data.cast<ffi.Void>();
      _eventCallbackOnErrorFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 0).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 1).ref.u64
          ..len = (returnBuf + 2).ref.u64
          ..data = (returnBuf + 3).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _eventCallbackOnEventFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_method_eventcallback_on_event');

  void eventCallbackInvokeOnEvent(int handle, String envelopeJson) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(4);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(4);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final int clonedHandle;
      {
        final cloneStatusPtr = calloc<_UniFfiRustCallStatus>();
        try {
          cloneStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
          cloneStatusPtr.ref.errorBuf
            ..capacity = 0
            ..len = 0
            ..data = ffi.nullptr;
          clonedHandle = _eventCallbackClone(handle, cloneStatusPtr);
          if (cloneStatusPtr.ref.code != _uniFfiRustCallStatusSuccess) {
            throw StateError('UniFFI clone failed with status ${cloneStatusPtr.ref.code}');
          }
        } finally {
          calloc.free(cloneStatusPtr);
        }
      }
      (argBuf + 0).ref.u64 = clonedHandle;
      final Uint8List envelopeJsonBytes = Uint8List.fromList(utf8.encode(envelopeJson));
      final ffi.Pointer<ffi.Uint8> envelopeJsonPtr = envelopeJsonBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(envelopeJsonBytes.length);
      if (envelopeJsonBytes.isNotEmpty) { envelopeJsonPtr.asTypedList(envelopeJsonBytes.length).setAll(0, envelopeJsonBytes); }
      foreignArgPtrs.add(envelopeJsonPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> envelopeJsonFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      envelopeJsonFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      envelopeJsonFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> envelopeJsonForeignPtr = calloc<_UniFfiForeignBytes>();
      envelopeJsonForeignPtr.ref
        ..len = envelopeJsonBytes.length
        ..data = envelopeJsonPtr;
      final _UniFfiRustBuffer envelopeJsonRustBuffer = _uniFfiRustBufferFromBytes(envelopeJsonForeignPtr.ref, envelopeJsonFromBytesStatusPtr);
      calloc.free(envelopeJsonForeignPtr);
      final int envelopeJsonFromBytesCode = envelopeJsonFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer envelopeJsonFromBytesErrBuf = envelopeJsonFromBytesStatusPtr.ref.errorBuf;
      calloc.free(envelopeJsonFromBytesStatusPtr);
      if (envelopeJsonFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> envelopeJsonFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        envelopeJsonFromBytesErrBufPtr.ref
          ..capacity = envelopeJsonFromBytesErrBuf.capacity
          ..len = envelopeJsonFromBytesErrBuf.len
          ..data = envelopeJsonFromBytesErrBuf.data;
        rustRetBufferPtrs.add(envelopeJsonFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $envelopeJsonFromBytesCode');
      }
      (argBuf + 1).ref.u64 = envelopeJsonRustBuffer.capacity;
      (argBuf + 2).ref.u64 = envelopeJsonRustBuffer.len;
      (argBuf + 3).ref.ptr = envelopeJsonRustBuffer.data.cast<ffi.Void>();
      _eventCallbackOnEventFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 0).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 1).ref.u64
          ..len = (returnBuf + 2).ref.u64
          ..data = (returnBuf + 3).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _frfFfiClientFreeRaw = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), void Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('uniffi_frf_ffi_fn_free_frffficlient');
  late final void Function(int handle) _frfFfiClientFree = (int handle) {
    final statusPtr = calloc<_UniFfiRustCallStatus>();
    statusPtr.ref.code = _uniFfiRustCallStatusSuccess;
    statusPtr.ref.errorBuf
      ..capacity = 0
      ..len = 0
      ..data = ffi.nullptr;
    _frfFfiClientFreeRaw(handle, statusPtr);
    calloc.free(statusPtr);
  };

  late final int Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _frfFfiClientClone = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), int Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('uniffi_frf_ffi_fn_clone_frffficlient');

  FrfFfiClient frfFfiClientCreateConnect(String endpoint, String? token) {
    throw UnsupportedError('runtime invocation for this UniFFI ABI (RustCallStatus out-arg) is not implemented yet (connect)');
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _frfFfiClientAckFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_method_frffficlient_ack');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _frfFfiClientAckFfiBufferRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('ffi_uniffi_frf_rust_future_poll_void');
  late final void Function(int handle) _frfFfiClientAckFfiBufferRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_frf_rust_future_cancel_void');
  late final void Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _frfFfiClientAckFfiBufferRustFutureComplete = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), void Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_frf_rust_future_complete_void');
  late final void Function(int handle) _frfFfiClientAckFfiBufferRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_frf_rust_future_free_void');

  Future<void> frfFfiClientInvokeAck(int handle, String channelId, String consumerId, int offset) async {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(8);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final int clonedHandle;
      {
        final cloneStatusPtr = calloc<_UniFfiRustCallStatus>();
        try {
          cloneStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
          cloneStatusPtr.ref.errorBuf
            ..capacity = 0
            ..len = 0
            ..data = ffi.nullptr;
          clonedHandle = _frfFfiClientClone(handle, cloneStatusPtr);
          if (cloneStatusPtr.ref.code != _uniFfiRustCallStatusSuccess) {
            throw StateError('UniFFI clone failed with status ${cloneStatusPtr.ref.code}');
          }
        } finally {
          calloc.free(cloneStatusPtr);
        }
      }
      (argBuf + 0).ref.u64 = clonedHandle;
      final Uint8List channelIdBytes = Uint8List.fromList(utf8.encode(channelId));
      final ffi.Pointer<ffi.Uint8> channelIdPtr = channelIdBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(channelIdBytes.length);
      if (channelIdBytes.isNotEmpty) { channelIdPtr.asTypedList(channelIdBytes.length).setAll(0, channelIdBytes); }
      foreignArgPtrs.add(channelIdPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> channelIdFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      channelIdFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      channelIdFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> channelIdForeignPtr = calloc<_UniFfiForeignBytes>();
      channelIdForeignPtr.ref
        ..len = channelIdBytes.length
        ..data = channelIdPtr;
      final _UniFfiRustBuffer channelIdRustBuffer = _uniFfiRustBufferFromBytes(channelIdForeignPtr.ref, channelIdFromBytesStatusPtr);
      calloc.free(channelIdForeignPtr);
      final int channelIdFromBytesCode = channelIdFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer channelIdFromBytesErrBuf = channelIdFromBytesStatusPtr.ref.errorBuf;
      calloc.free(channelIdFromBytesStatusPtr);
      if (channelIdFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> channelIdFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        channelIdFromBytesErrBufPtr.ref
          ..capacity = channelIdFromBytesErrBuf.capacity
          ..len = channelIdFromBytesErrBuf.len
          ..data = channelIdFromBytesErrBuf.data;
        rustRetBufferPtrs.add(channelIdFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $channelIdFromBytesCode');
      }
      (argBuf + 1).ref.u64 = channelIdRustBuffer.capacity;
      (argBuf + 2).ref.u64 = channelIdRustBuffer.len;
      (argBuf + 3).ref.ptr = channelIdRustBuffer.data.cast<ffi.Void>();
      final Uint8List consumerIdBytes = Uint8List.fromList(utf8.encode(consumerId));
      final ffi.Pointer<ffi.Uint8> consumerIdPtr = consumerIdBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(consumerIdBytes.length);
      if (consumerIdBytes.isNotEmpty) { consumerIdPtr.asTypedList(consumerIdBytes.length).setAll(0, consumerIdBytes); }
      foreignArgPtrs.add(consumerIdPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> consumerIdFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      consumerIdFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      consumerIdFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> consumerIdForeignPtr = calloc<_UniFfiForeignBytes>();
      consumerIdForeignPtr.ref
        ..len = consumerIdBytes.length
        ..data = consumerIdPtr;
      final _UniFfiRustBuffer consumerIdRustBuffer = _uniFfiRustBufferFromBytes(consumerIdForeignPtr.ref, consumerIdFromBytesStatusPtr);
      calloc.free(consumerIdForeignPtr);
      final int consumerIdFromBytesCode = consumerIdFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer consumerIdFromBytesErrBuf = consumerIdFromBytesStatusPtr.ref.errorBuf;
      calloc.free(consumerIdFromBytesStatusPtr);
      if (consumerIdFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> consumerIdFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        consumerIdFromBytesErrBufPtr.ref
          ..capacity = consumerIdFromBytesErrBuf.capacity
          ..len = consumerIdFromBytesErrBuf.len
          ..data = consumerIdFromBytesErrBuf.data;
        rustRetBufferPtrs.add(consumerIdFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $consumerIdFromBytesCode');
      }
      (argBuf + 4).ref.u64 = consumerIdRustBuffer.capacity;
      (argBuf + 5).ref.u64 = consumerIdRustBuffer.len;
      (argBuf + 6).ref.ptr = consumerIdRustBuffer.data.cast<ffi.Void>();
      (argBuf + 7).ref.u64 = offset;
      _frfFfiClientAckFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer async start failed with status $statusCode');
      }
      final int futureHandle = (returnBuf + 0).ref.u64;
      final StreamController<int> pollEvents = StreamController<int>.broadcast();
      final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
        pollEvents.add(pollResult);
      });
      try {
        _frfFfiClientAckFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
        while (true) {
          final int pollResult = await pollEvents.stream.first;
          if (pollResult == _rustFuturePollReady) {
            break;
          }
          if (pollResult == _rustFuturePollWake) {
            _frfFfiClientAckFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
            continue;
          }
          throw StateError('Rust future poll returned invalid status for ack: $pollResult');
        }
        final ffi.Pointer<_UniFfiRustCallStatus> outStatusPtr = calloc<_UniFfiRustCallStatus>();
        outStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        outStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        try {
          _frfFfiClientAckFfiBufferRustFutureComplete(futureHandle, outStatusPtr);
          final int completeStatusCode = outStatusPtr.ref.code;
          if (completeStatusCode == _uniFfiRustCallStatusSuccess) {
            return;
          }
          if (completeStatusCode == _uniFfiRustCallStatusCancelled) {
            throw StateError('Rust future was cancelled for ack');
          }
          final _UniFfiRustBuffer errorBuf = outStatusPtr.ref.errorBuf;
          if (!(errorBuf.data == ffi.nullptr && errorBuf.len == 0 && errorBuf.capacity == 0)) {
            final ffi.Pointer<_UniFfiRustBuffer> errorBufPtr = calloc<_UniFfiRustBuffer>();
            errorBufPtr.ref
              ..capacity = errorBuf.capacity
              ..len = errorBuf.len
              ..data = errorBuf.data;
            rustRetBufferPtrs.add(errorBufPtr);
            final Uint8List errorBytes = errorBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errorBufPtr.ref.data.asTypedList(errorBufPtr.ref.len));
            if (completeStatusCode == _uniFfiRustCallStatusError && errorBytes.isNotEmpty) {
              throw _uniffiLiftClientFfiErrorException(errorBytes);
            }
            if (errorBytes.isNotEmpty) {
              throw StateError(utf8.decode(errorBytes, allowMalformed: true));
            }
          }
          throw StateError('Rust future failed for ack with status code: $completeStatusCode');
        } finally {
          calloc.free(outStatusPtr);
        }
      } catch (_) {
        _frfFfiClientAckFfiBufferRustFutureCancel(futureHandle);
        rethrow;
      } finally {
        await pollEvents.close();
        callback.close();
        _frfFfiClientAckFfiBufferRustFutureFree(futureHandle);
      }
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _frfFfiClientPublishFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_method_frffficlient_publish');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _frfFfiClientPublishFfiBufferRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('ffi_uniffi_frf_rust_future_poll_u64');
  late final void Function(int handle) _frfFfiClientPublishFfiBufferRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_frf_rust_future_cancel_u64');
  late final int Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _frfFfiClientPublishFfiBufferRustFutureComplete = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), int Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_frf_rust_future_complete_u64');
  late final void Function(int handle) _frfFfiClientPublishFfiBufferRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_frf_rust_future_free_u64');

  Future<int> frfFfiClientInvokePublish(int handle, String envelopeJson) async {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(4);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final int clonedHandle;
      {
        final cloneStatusPtr = calloc<_UniFfiRustCallStatus>();
        try {
          cloneStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
          cloneStatusPtr.ref.errorBuf
            ..capacity = 0
            ..len = 0
            ..data = ffi.nullptr;
          clonedHandle = _frfFfiClientClone(handle, cloneStatusPtr);
          if (cloneStatusPtr.ref.code != _uniFfiRustCallStatusSuccess) {
            throw StateError('UniFFI clone failed with status ${cloneStatusPtr.ref.code}');
          }
        } finally {
          calloc.free(cloneStatusPtr);
        }
      }
      (argBuf + 0).ref.u64 = clonedHandle;
      final Uint8List envelopeJsonBytes = Uint8List.fromList(utf8.encode(envelopeJson));
      final ffi.Pointer<ffi.Uint8> envelopeJsonPtr = envelopeJsonBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(envelopeJsonBytes.length);
      if (envelopeJsonBytes.isNotEmpty) { envelopeJsonPtr.asTypedList(envelopeJsonBytes.length).setAll(0, envelopeJsonBytes); }
      foreignArgPtrs.add(envelopeJsonPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> envelopeJsonFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      envelopeJsonFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      envelopeJsonFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> envelopeJsonForeignPtr = calloc<_UniFfiForeignBytes>();
      envelopeJsonForeignPtr.ref
        ..len = envelopeJsonBytes.length
        ..data = envelopeJsonPtr;
      final _UniFfiRustBuffer envelopeJsonRustBuffer = _uniFfiRustBufferFromBytes(envelopeJsonForeignPtr.ref, envelopeJsonFromBytesStatusPtr);
      calloc.free(envelopeJsonForeignPtr);
      final int envelopeJsonFromBytesCode = envelopeJsonFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer envelopeJsonFromBytesErrBuf = envelopeJsonFromBytesStatusPtr.ref.errorBuf;
      calloc.free(envelopeJsonFromBytesStatusPtr);
      if (envelopeJsonFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> envelopeJsonFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        envelopeJsonFromBytesErrBufPtr.ref
          ..capacity = envelopeJsonFromBytesErrBuf.capacity
          ..len = envelopeJsonFromBytesErrBuf.len
          ..data = envelopeJsonFromBytesErrBuf.data;
        rustRetBufferPtrs.add(envelopeJsonFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $envelopeJsonFromBytesCode');
      }
      (argBuf + 1).ref.u64 = envelopeJsonRustBuffer.capacity;
      (argBuf + 2).ref.u64 = envelopeJsonRustBuffer.len;
      (argBuf + 3).ref.ptr = envelopeJsonRustBuffer.data.cast<ffi.Void>();
      _frfFfiClientPublishFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer async start failed with status $statusCode');
      }
      final int futureHandle = (returnBuf + 0).ref.u64;
      final StreamController<int> pollEvents = StreamController<int>.broadcast();
      final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
        pollEvents.add(pollResult);
      });
      try {
        _frfFfiClientPublishFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
        while (true) {
          final int pollResult = await pollEvents.stream.first;
          if (pollResult == _rustFuturePollReady) {
            break;
          }
          if (pollResult == _rustFuturePollWake) {
            _frfFfiClientPublishFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
            continue;
          }
          throw StateError('Rust future poll returned invalid status for publish: $pollResult');
        }
        final ffi.Pointer<_UniFfiRustCallStatus> outStatusPtr = calloc<_UniFfiRustCallStatus>();
        outStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        outStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        try {
          final int resultValue = _frfFfiClientPublishFfiBufferRustFutureComplete(futureHandle, outStatusPtr);
          final int completeStatusCode = outStatusPtr.ref.code;
          if (completeStatusCode == _uniFfiRustCallStatusSuccess) {
            return resultValue;
          }
          if (completeStatusCode == _uniFfiRustCallStatusCancelled) {
            throw StateError('Rust future was cancelled for publish');
          }
          final _UniFfiRustBuffer errorBuf = outStatusPtr.ref.errorBuf;
          if (!(errorBuf.data == ffi.nullptr && errorBuf.len == 0 && errorBuf.capacity == 0)) {
            final ffi.Pointer<_UniFfiRustBuffer> errorBufPtr = calloc<_UniFfiRustBuffer>();
            errorBufPtr.ref
              ..capacity = errorBuf.capacity
              ..len = errorBuf.len
              ..data = errorBuf.data;
            rustRetBufferPtrs.add(errorBufPtr);
            final Uint8List errorBytes = errorBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errorBufPtr.ref.data.asTypedList(errorBufPtr.ref.len));
            if (completeStatusCode == _uniFfiRustCallStatusError && errorBytes.isNotEmpty) {
              throw _uniffiLiftClientFfiErrorException(errorBytes);
            }
            if (errorBytes.isNotEmpty) {
              throw StateError(utf8.decode(errorBytes, allowMalformed: true));
            }
          }
          throw StateError('Rust future failed for publish with status code: $completeStatusCode');
        } finally {
          calloc.free(outStatusPtr);
        }
      } catch (_) {
        _frfFfiClientPublishFfiBufferRustFutureCancel(futureHandle);
        rethrow;
      } finally {
        await pollEvents.close();
        callback.close();
        _frfFfiClientPublishFfiBufferRustFutureFree(futureHandle);
      }
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _frfFfiClientSubscribeFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_frf_ffi_fn_method_frffficlient_subscribe');

  void frfFfiClientInvokeSubscribe(int handle, String channelId, String consumerId, int fromOffset, EventCallback callback) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(9);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(4);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final int clonedHandle;
      {
        final cloneStatusPtr = calloc<_UniFfiRustCallStatus>();
        try {
          cloneStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
          cloneStatusPtr.ref.errorBuf
            ..capacity = 0
            ..len = 0
            ..data = ffi.nullptr;
          clonedHandle = _frfFfiClientClone(handle, cloneStatusPtr);
          if (cloneStatusPtr.ref.code != _uniFfiRustCallStatusSuccess) {
            throw StateError('UniFFI clone failed with status ${cloneStatusPtr.ref.code}');
          }
        } finally {
          calloc.free(cloneStatusPtr);
        }
      }
      (argBuf + 0).ref.u64 = clonedHandle;
      final Uint8List channelIdBytes = Uint8List.fromList(utf8.encode(channelId));
      final ffi.Pointer<ffi.Uint8> channelIdPtr = channelIdBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(channelIdBytes.length);
      if (channelIdBytes.isNotEmpty) { channelIdPtr.asTypedList(channelIdBytes.length).setAll(0, channelIdBytes); }
      foreignArgPtrs.add(channelIdPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> channelIdFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      channelIdFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      channelIdFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> channelIdForeignPtr = calloc<_UniFfiForeignBytes>();
      channelIdForeignPtr.ref
        ..len = channelIdBytes.length
        ..data = channelIdPtr;
      final _UniFfiRustBuffer channelIdRustBuffer = _uniFfiRustBufferFromBytes(channelIdForeignPtr.ref, channelIdFromBytesStatusPtr);
      calloc.free(channelIdForeignPtr);
      final int channelIdFromBytesCode = channelIdFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer channelIdFromBytesErrBuf = channelIdFromBytesStatusPtr.ref.errorBuf;
      calloc.free(channelIdFromBytesStatusPtr);
      if (channelIdFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> channelIdFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        channelIdFromBytesErrBufPtr.ref
          ..capacity = channelIdFromBytesErrBuf.capacity
          ..len = channelIdFromBytesErrBuf.len
          ..data = channelIdFromBytesErrBuf.data;
        rustRetBufferPtrs.add(channelIdFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $channelIdFromBytesCode');
      }
      (argBuf + 1).ref.u64 = channelIdRustBuffer.capacity;
      (argBuf + 2).ref.u64 = channelIdRustBuffer.len;
      (argBuf + 3).ref.ptr = channelIdRustBuffer.data.cast<ffi.Void>();
      final Uint8List consumerIdBytes = Uint8List.fromList(utf8.encode(consumerId));
      final ffi.Pointer<ffi.Uint8> consumerIdPtr = consumerIdBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(consumerIdBytes.length);
      if (consumerIdBytes.isNotEmpty) { consumerIdPtr.asTypedList(consumerIdBytes.length).setAll(0, consumerIdBytes); }
      foreignArgPtrs.add(consumerIdPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> consumerIdFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      consumerIdFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      consumerIdFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> consumerIdForeignPtr = calloc<_UniFfiForeignBytes>();
      consumerIdForeignPtr.ref
        ..len = consumerIdBytes.length
        ..data = consumerIdPtr;
      final _UniFfiRustBuffer consumerIdRustBuffer = _uniFfiRustBufferFromBytes(consumerIdForeignPtr.ref, consumerIdFromBytesStatusPtr);
      calloc.free(consumerIdForeignPtr);
      final int consumerIdFromBytesCode = consumerIdFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer consumerIdFromBytesErrBuf = consumerIdFromBytesStatusPtr.ref.errorBuf;
      calloc.free(consumerIdFromBytesStatusPtr);
      if (consumerIdFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> consumerIdFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        consumerIdFromBytesErrBufPtr.ref
          ..capacity = consumerIdFromBytesErrBuf.capacity
          ..len = consumerIdFromBytesErrBuf.len
          ..data = consumerIdFromBytesErrBuf.data;
        rustRetBufferPtrs.add(consumerIdFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $consumerIdFromBytesCode');
      }
      (argBuf + 4).ref.u64 = consumerIdRustBuffer.capacity;
      (argBuf + 5).ref.u64 = consumerIdRustBuffer.len;
      (argBuf + 6).ref.ptr = consumerIdRustBuffer.data.cast<ffi.Void>();
      (argBuf + 7).ref.u64 = fromOffset;
      (argBuf + 8).ref.u64 = callback;
      _frfFfiClientSubscribeFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 0).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 1).ref.u64
          ..len = (returnBuf + 2).ref.u64
          ..data = (returnBuf + 3).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftClientFfiErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }
}

/// Callback the host app implements to receive subscription events.
///
/// `on_event` is called once per delivered envelope (as a JSON string).
/// `on_error` is called if the stream fails; after it, no further events arrive.
abstract interface class EventCallback {
  void onError(String message);
  void onEvent(String envelopeJson);
}

final class _EventCallbackFinalizerToken {
  const _EventCallbackFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class _EventCallbackImpl implements EventCallback {
  _EventCallbackImpl._(this._ffi, this._handle) {
    _finalizer.attach(this, _EventCallbackFinalizerToken(_ffi._eventCallbackFree, _handle), detach: this);
  }

  final FrfFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_EventCallbackFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._eventCallbackFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('_EventCallbackImpl is closed');
    }
  }

  @override
  void onError(String message) {
    _ensureOpen();
    _ffi.eventCallbackInvokeOnError(_handle, message);
  }

  @override
  void onEvent(String envelopeJson) {
    _ensureOpen();
    _ffi.eventCallbackInvokeOnEvent(_handle, envelopeJson);
  }

}

final class _EventCallbackTraitVTable extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle)>> uniffiFree;

  external ffi.Pointer<ffi.NativeFunction<ffi.Uint64 Function(ffi.Uint64 handle)>> uniffiClone;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> message, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> onError;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> envelopeJson, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> onEvent;

}

final class _EventCallbackTraitCallbackBridge {
  _EventCallbackTraitCallbackBridge._();
  static final _EventCallbackTraitCallbackBridge instance = _EventCallbackTraitCallbackBridge._();

  final Map<int, EventCallback> _callbacks = <int, EventCallback>{};
  final Map<int, int> _refCounts = <int, int>{};
  int _nextHandle = 1;

  int register(EventCallback callback) {
    final int handle = _nextHandle;
    _nextHandle += 2;
    _callbacks[handle] = callback;
    _refCounts[handle] = 1;
    return handle;
  }

  void release(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      return;
    }
    if (refs <= 1) {
      _refCounts.remove(handle);
      _callbacks.remove(handle);
      return;
    }
    _refCounts[handle] = refs - 1;
  }

  int cloneHandle(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      throw StateError('Invalid callback handle: $handle');
    }
    _refCounts[handle] = refs + 1;
    return handle;
  }

  EventCallback? lookup(int handle) => _callbacks[handle];

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)> _freeNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    instance.release(handle);
  });

  static final ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)> _cloneNative = ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    return instance.cloneHandle(handle);
  }, exceptionalReturn: 0);

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> message, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _onErrorNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> message, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> message, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final EventCallback? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      callback.onError(message == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : message.toDartString());
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = err.toString().toNativeUtf8();
    }
  });

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> envelopeJson, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _onEventNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> envelopeJson, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> envelopeJson, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final EventCallback? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      callback.onEvent(envelopeJson == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : envelopeJson.toDartString());
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = err.toString().toNativeUtf8();
    }
  });

  static ffi.Pointer<_EventCallbackTraitVTable> createVTable() {
    final ffi.Pointer<_EventCallbackTraitVTable> vtablePtr = calloc<_EventCallbackTraitVTable>();
    vtablePtr.ref
      ..uniffiFree = _freeNative.nativeFunction
      ..uniffiClone = _cloneNative.nativeFunction
      ..onError = _onErrorNative.nativeFunction
      ..onEvent = _onEventNative.nativeFunction
    ;
    return vtablePtr;
  }
}

final class EventCallbackFfiCodec {
  const EventCallbackFfiCodec._();

  static int lower(EventCallback value) {
    if (value is _EventCallbackImpl) {
      return value._handle;
    }
    _bindings()._eventCallbackTraitCallbackInitDone;
    return _EventCallbackTraitCallbackBridge.instance.register(value);
  }

  static EventCallback lift(int handle) => _EventCallbackImpl._(_bindings(), handle);
}

final class _FrfFfiClientFinalizerToken {
  const _FrfFfiClientFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

/// A connected Flint Realtime Fabric client.
///
/// Wraps the hand-written Rust SDK ([`FrfClient`]). Construct with
/// [`FrfFfiClient::connect`], then `publish` / `subscribe` / `ack`. `subscribe` is
/// resilient: it reconnects with backoff and resumes from the last offset, so mobile
/// clients survive gateway restarts without special handling.
final class FrfFfiClient {
  FrfFfiClient._(this._ffi, this._handle) {
    _finalizer.attach(this, _FrfFfiClientFinalizerToken(_ffi._frfFfiClientFree, _handle), detach: this);
  }

  final FrfFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_FrfFfiClientFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._frfFfiClientFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('FrfFfiClient is closed');
    }
  }

  /// Connect to the gateway's gRPC endpoint, optionally with a bearer token.
  ///
  /// # Errors
  ///
  /// Returns [`ClientFfiError::Connect`] if the endpoint is invalid or the
  /// transport connection fails.
  static Future<FrfFfiClient> connect(String endpoint, String? token) {
    return _bindings().frfFfiClientCreateConnect(endpoint, token);
  }

  /// Acknowledge consumption up to `offset` for a channel/consumer.
  ///
  /// # Errors
  ///
  /// Returns [`ClientFfiError::InvalidArgument`] if `channel_id` is not a UUID, or
  /// [`ClientFfiError::Request`] if the ack RPC fails.
  Future<void> ack(String channelId, String consumerId, int offset) {
    _ensureOpen();
    return _ffi.frfFfiClientInvokeAck(_handle, channelId, consumerId, offset);
  }

  /// Publish an event (given as a JSON `EventEnvelope`), returning the offset.
  ///
  /// # Errors
  ///
  /// Returns [`ClientFfiError::InvalidArgument`] if the JSON is not a valid
  /// envelope, or [`ClientFfiError::Request`] if the gateway rejects it.
  Future<int> publish(String envelopeJson) {
    _ensureOpen();
    return _ffi.frfFfiClientInvokePublish(_handle, envelopeJson);
  }

  /// Subscribe to a channel. Events are delivered to `callback` until the
  /// stream ends or errors. Returns immediately after validating the channel id;
  /// delivery runs on a background task.
  ///
  /// The subscription is **resilient**: on a transport error or gateway restart it
  /// reconnects with exponential backoff and resumes from the last delivered offset,
  /// so no event is skipped. `callback.on_error` fires only if reconnection is
  /// permanently exhausted.
  ///
  /// # Errors
  ///
  /// Returns [`ClientFfiError::InvalidArgument`] if `channel_id` is not a UUID.
  void subscribe(String channelId, String consumerId, int fromOffset, EventCallback callback) {
    _ensureOpen();
    _ffi.frfFfiClientInvokeSubscribe(_handle, channelId, consumerId, fromOffset, callback);
  }

}

final class FrfFfiClientFfiCodec {
  const FrfFfiClientFfiCodec._();

  static int lower(FrfFfiClient value) => value._handle;

  static FrfFfiClient lift(int handle) => FrfFfiClient._(_bindings(), handle);
}

FrfFfi? _defaultBindings;

FrfFfi _bindings() => _defaultBindings ??= FrfFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = FrfFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

/// Apply a Loro CRDT delta to an existing snapshot, returning a new snapshot.
///
/// Both `existing` and `delta` are engine-opaque bytes. Pass an empty `Vec`
/// for `existing` when no prior state exists.
///
/// Exposed to Swift, Kotlin, and Dart via `UniFFI`.
///
/// # Errors
///
/// Returns `CrdtFfiError::ApplyDelta` if the merge fails.
Uint8List crdtApplyDelta(Uint8List existing, Uint8List delta) {
  return _bindings().crdtApplyDelta(existing, delta);
}

/// Return an empty Loro snapshot (new document with no ops).
///
/// Useful for initialising a local entity store before the first server sync.
///
/// # Errors
///
/// Returns `CrdtFfiError::Encode` if the Loro document cannot be exported.
Uint8List crdtNewSnapshot() {
  return _bindings().crdtNewSnapshot();
}

/// Return the version number (Lamport clock) of a Loro snapshot.
///
/// Returns `0` if the bytes are empty or cannot be decoded.
int crdtSnapshotVersion(Uint8List snapshot) {
  return _bindings().crdtSnapshotVersion(snapshot);
}

