apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frf-gateway
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: frf-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frf-iggy
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: frf-iggy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frf-keto-postgres
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: frf-keto-postgres
