#!/usr/bin/env bash
# Enforce CLAUDE.md's file-size rule: no file over 500 lines, any language.
#
# The cap is declared in CLAUDE.md ("File Size Limit") and in
# .kbd-orchestrator/constraints.md as R5 (BLOCKING) — and until p38-c004 it was
# enforced by nothing, which is how crates/frf-gateway/src/main.rs crossed it
# silently at 504 lines.
#
# Usage:
#   scripts/check-file-size.sh            # check the repo, exit 1 on any overage
#   MAX_LINES=300 scripts/check-file-size.sh
#
# CI may run this: it is a lint, not a test. AGENTS.md permits CI for "build,
# lint, typecheck, formatting and packaging" and forbids it for tests.

set -euo pipefail

MAX_LINES="${MAX_LINES:-500}"
# Warn when a file is within this many lines of the cap, so the next overage is
# anticipated rather than discovered.
WARN_WITHIN="${WARN_WITHIN:-25}"

cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Hand-written source only. Generated output is excluded deliberately: a gate
# that fires on code nobody wrote invites an exception, and an exception is how
# a guard stops being believed. The repo already treats generated output as
# out-of-band (.gitignore excludes proto/gen/ and the Dart frb_generated.* set).
# Tracked files AND untracked-but-not-ignored ones. `git ls-files` alone lists
# only tracked paths, which means a brand-new oversized file passes locally until
# it is staged — harmless in CI (checkout yields a fully tracked tree) but wrong
# on a developer's machine, where the newest file is exactly the one most likely
# to be over. Found by sabotage-testing this script in p38-c004, not by reading it.
# `--exclude-standard` keeps .gitignore honoured, so generated/ignored output
# stays out.
mapfile -t FILES < <(
  {
    git ls-files \
      '*.rs' '*.ts' '*.tsx' '*.js' '*.jsx' '*.py' '*.go' '*.kt' '*.swift' '*.dart'
    git ls-files --others --exclude-standard \
      '*.rs' '*.ts' '*.tsx' '*.js' '*.jsx' '*.py' '*.go' '*.kt' '*.swift' '*.dart'
  } \
  | sort -u \
  | grep -vE '(^|/)(gen|generated|dist|node_modules|target)/' \
  | grep -vE '_pb\.(ts|js)$|\.pb\.go$|frb_generated' \
  || true
)

over=0
near=0
over_list=()
near_list=()

for f in "${FILES[@]}"; do
  [ -f "$f" ] || continue
  # Skip files carrying a generator marker in their first few lines.
  if head -5 "$f" 2>/dev/null | grep -qiE '@generated|Code generated by|DO NOT EDIT'; then
    continue
  fi
  n=$(wc -l < "$f" | tr -d ' ')
  if [ "$n" -gt "$MAX_LINES" ]; then
    over=$((over + 1)); over_list+=("$n	$f")
  elif [ "$n" -gt $((MAX_LINES - WARN_WITHIN)) ]; then
    near=$((near + 1)); near_list+=("$n	$f")
  fi
done

if [ "$near" -gt 0 ]; then
  printf 'Within %d lines of the %d-line cap (not a failure):\n' "$WARN_WITHIN" "$MAX_LINES"
  printf '%s\n' "${near_list[@]}" | sort -rn | sed 's/^/  /'
  echo
fi

if [ "$over" -gt 0 ]; then
  printf 'FAIL: %d file(s) over the %d-line cap:\n' "$over" "$MAX_LINES"
  printf '%s\n' "${over_list[@]}" | sort -rn | sed 's/^/  /'
  echo
  echo 'Split the file into a directory module (CLAUDE.md, "File Size Limit").'
  exit 1
fi

printf 'PASS: no file over %d lines (%d checked, %d near the cap).\n' \
  "$MAX_LINES" "${#FILES[@]}" "$near"
